config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'translate#index'
  post '/' => 'translate#index'

  resources :users, only: [:new, :create, :show, :edit]
  resources :user_sessions, only: [:create, :destroy]

  delete 'sign_out' => 'user_sessions#destroy', as: :sign_out

  get 'sign_in' => 'user_sessions#new', as: :sign_in
  post 'sign_in' => 'user_sessions#create', as: :sign_in_post

  get 'sign_up' => 'users#new', as: :sign_up
  post 'sign_up' => 'users#create', as: :sign_up_post

  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id/edit' => 'users#update'

  namespace :api do
    namespace :v1 do
      get '/translate' => 'translate#translate'
      post '/translate' => 'translate#translate'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :user
  # validates :input, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic
  has_many :translations, dependent: :destroy
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
end

app/controllers/api/v1/translate_controller.rb
require 'yaml'

class Api::V1::TranslateController < Api::V1::BaseController
  def translate
    if params[:yaml]
      data = YAML.load(params[:yaml].tempfile)

      out_tree = YmlTranslate.tr(data, params[:input_lang], params[:output_lang])

      render plain: out_tree.to_yaml, content_type: 'text/yaml', status: 200
    else
      o = YandexWrapper.translate(params[:input], params[:input_lang], params[:output_lang])
      render json: o[:output], status: 200
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :permission_denied

  protect_from_forgery with: :exception
  before_action :set_locale
  helper_method :current_user_session, :current_user

  def set_locale
    if current_user
      I18n.locale = current_user.lang
    else
      I18n.locale = I18n.default_locale
    end
  end

  private

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def permission_denied
      flash[:danger] = t("Authorization error")
      redirect_to request.referrer || root_path
    end
end

app/controllers/translate_controller.rb
class TranslateController < ApplicationController
  def index
    @form = TranslateForm.new(Translation.new)
    @lang_list = LANG_LIST[I18n.locale]

    if request.post?
      translation = YandexWrapper.translate(params[:translate][:input],
                                     params[:translate][:input_lang],
                                     params[:translate][:output_lang])
      if translation[:error]
        flash.now[translation[:error][:type]] = translation[:error][:message]
      else
        params[:translate][:output] = translation[:output]

        if params[:translate][:input_lang].blank?
          params[:translate][:input_lang] = translation[:detected]
        end

        if @form.validate(params[:translate])
          @form.save
        end
      end
    elsif request.get?
      params[:translate] = {}
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      # I18n.locale = current_user.lang
      flash[:success] = t("Welcome back!")
      redirect_to root_path
    else
      flash[:danger] = t("Wrong email or password!")
      render :new
      # redirect_to sign_in_path
    end
  end

  def destroy
    if current_user_session
      current_user_session.destroy
      flash[:success] = t("Goodbye!")
    end
    redirect_to root_path
  end

  private

    def user_session_params
      params.require(:user_session).permit(:email, :password, :remember_me, :test)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = 'Account registered!'
      redirect_to root_path
    else
      render new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user

    @translations = @user.translations.paginate(page: params[:page], :per_page => 5)
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update_attributes(users_params)
      I18n.locale = users_params[:lang]
      flash.now[:success] = t(:language_changed)
    else
      flash.now[:danger] = 'Language didn\'t updated'
    end

    render :edit
  end

  private

    def users_params
      params.require(:user).permit(:email, :password, :password_confirmation, :lang)
    end
end

app/views/layouts/_footer.html.slim
footer.footer
  .container
    .row
      nav
        ul#footer-left.pull-left
          li
            = t('powered')
            a[href="http://translate.yandex.ru"]
              = " " + t('YandexTranslate')
        ul.pull-right
          li
            = link_to t("about"), 'https://github.com/Eeeeevgen/Translator', target: :_blank
          li
            = link_to t("contact"), 'mailto: kozlov.evg.a@gmail.com'

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target="#myNavbar"]
        span.icon-bar
        span.icon-bar
        span.icon-bar
    #myNavbar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to t("home"), root_path
        - if current_user
          li.dropdown
            a.dropdown-toggle[data-toggle="dropdown"]
              = t('account') + ": "
              b
                = current_user[:email]
              b.caret
            ul.dropdown-menu
              li
                = link_to t("translation_history"), user_path(current_user)
              li
                = link_to t("settings"), edit_user_path(current_user)
          li
            = link_to t('sign_out'), sign_out_path, method: :delete
        - else
          li
            = link_to t("sign_up"), sign_up_path
          li
            = link_to t('sign_in'), sign_in_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:title)
    = csrf_meta_tags
    script[src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"]
    script[src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      = content_tag(:div, message, class: "alert alert-#{message_type}")
    .container
      = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      |  Found 
      = pluralize(@user.errors.count, "error")
      | : 
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/translate/index.html.slim
- provide(:title, t('translator'))

= form_for @form, url:"/", method: :post  do |f|
  - if current_user
    = f.hidden_field :user_id, { value: current_user.id}
  .row
    .col-xs-6.form-group
      = f.text_area :input, { value: params[:translate][:input], class: 'form-control' }
    .col-xs-6.form-group
      = text_area_tag :output, params[:translate][:output], { readonly: true, class:'form-control' }
  .row.row-centered
    .col-centered
      = f.select :input_lang,
              options_for_select([[t('auto'), '']] + @lang_list, params[:translate][:input_lang]),
              {},
              { class: 'selectpicker form-control' }
    .col-centered
      = f.select :output_lang,
              options_for_select(@lang_list, params[:translate][:output_lang]),
              {},
              { class: 'selectpicker form-control' }
  .row.row-centered
    .col-centered
      = f.submit t("translate"), { class:'btn btn-primary' }

app/views/user_sessions/new.html.slim
- provide(:title, t("log_in"))
h1
  = t("sign_in_h")
.row
  .col-md-6.col-md-offset-3
    = form_for @user_session, url: :sign_in_post do |f|
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password, t("password")
      = f.password_field :password, class: 'form-control'
      = f.label :remember_me, class: "checkbox inline" do
        = f.check_box :remember_me
        span
          = t('remember')
      = f.submit t("log_in"), class: "btn btn-primary"

app/views/users/edit.html.slim
- provide(:title, t('settings'))
h1
  = t('settings')
.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url:edit_user_path(current_user), html:{class:'form-inline', id:'edit_lang'}) do |f|
      = f.label :lang, t('choose_language')+':'
      = f.select(:lang,
                            options_for_select([[t('english'), 'en'], [t('russian'), 'ru']], @user[:lang]),
                            {},
                            {class:'selectpicker form-control'})
      = button_tag t("save"), class: "btn btn-primary"

app/views/users/new.html.slim
- provide(:title, t('sign_up'))
h1
  = t('sign_up_h')
.row
  .col-md-6.col-md-offset-3
    = form_for @user, url: :sign_up_post do |f|
      = render 'shared/error_messages', object: @user
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password, t('password')
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, t("password_confirmation")
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit t("register"), class: "btn btn-primary"

app/views/users/show.html.slim
- provide(:title, t('translation_history'))
h1
  = t('translation_history')

= will_paginate @translations, inner_window: 2, outer_window: 0

table#history.table.table-bordered.table-striped[style="word-wrap: break-word"]
  tr
    th
      = Translation.human_attribute_name('created_at')
    th
      = Translation.human_attribute_name('input_lang')
    th
      = Translation.human_attribute_name('output_lang')
    th
      = Translation.human_attribute_name('input')
    th
      = Translation.human_attribute_name('output')
  - @translations.each do |translation|
    tr
      td
        = translation.created_at.strftime('%d.%m.%Y %H:%M:%S')
      td
        = LANG_LIST_RAW[I18n.locale][translation.input_lang]
      td
        = LANG_LIST_RAW[I18n.locale][translation.output_lang]
      td
        = translation.input
      td
        = translation.output

= will_paginate @translations, inner_window: 1, outer_window: 0